const types = {
  RESET_CALC_STATE: 'calc/RESET_CALC_STATE',
  SET_INPUT_VALUE: 'calc/SET_INPUT_VALUE',
  SET_MATHQUILL_VALUE: 'calc/SET_MATHQUILL_VALUE',
  SET_VALUE_A: 'calc/SET_VALUE_A',
  SET_VALUE_B: 'calc/SET_VALUE_B',
  SET_RESULT: 'calc/SET_RESULT',
  SET_OPERATOR: 'calc/SET_OPERATOR',
  SET_RESET_COUNTER: 'calc/SET_RESET_COUNTER',

  SET_BUTTONS: 'calc/SET_BUTTONS',
  SET_BUTTON_IS_CLICKED: 'calc/SET_BUTTON_IS_CLICKED',
};

export default types;
